# Generated by Django 5.1.6 on 2025-09-23 20:01

import utils.generate_ids
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TTSStudio', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voices',
            fields=[
                ('id', models.BigIntegerField(default=utils.generate_ids.generate_unique_id, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('language', models.CharField(choices=[('en-us', 'english-us'), ('en-br', 'english-britain')], default='en-us', max_length=50)),
                ('file', models.FileField(upload_to='')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('is_premium', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='ttsmodel',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='ttsmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ttsmodel',
            name='id',
            field=models.BigIntegerField(default=utils.generate_ids.generate_unique_id, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
