# Generated by Django 5.1.6 on 2025-09-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TTSStudio', '0003_voices_alter_ttsmodel_options_ttsmodel_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voices',
            name='file',
            field=models.FileField(upload_to='voices'),
        ),
    ]
