# Generated by Django 5.1.6 on 2025-09-24 09:28

import django.db.models.deletion
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TTSStudio", "0005_voice_delete_voices"),
    ]

    operations = [
        migrations.AddField(
            model_name="ttssession",
            name="energy",
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name="ttssession",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ttssession",
            name="filename",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="ttssession",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("error", "Error"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="ttssession",
            name="text_length",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="ttssession",
            name="voice",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="TTSStudio.voice",
            ),
        ),
        migrations.AlterField(
            model_name="ttssession",
            name="audio_file",
            field=models.FileField(
                null=True,
                upload_to=pathlib.PurePosixPath(
                    "/home/skye/EchoVerse/Backend/uploads/tts_audio"
                ),
            ),
        ),
    ]
