# Generated by Django 5.1.6 on 2025-09-25 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TTSStudio', '0006_ttssession_energy_ttssession_error_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ttssession',
            name='filename',
        ),
        migrations.AlterField(
            model_name='ttssession',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/tts_audio/'),
        ),
        migrations.AlterField(
            model_name='ttssession',
            name='text_length',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ttssession',
            name='voice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TTSStudio.voice'),
        ),
        migrations.AlterField(
            model_name='voice',
            name='file',
            field=models.FileField(upload_to='voices/'),
        ),
    ]
