# Generated by Django 5.1.6 on 2025-09-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TTSStudio', '0007_remove_ttssession_filename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voice',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='voices/'),
        ),
    ]
