# Generated by Django 5.1.6 on 2025-09-30 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TTSStudio', '0008_alter_voice_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='voice',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_voice_ownner', to='TTSStudio.ttsmodel'),
        ),
        migrations.AlterField(
            model_name='ttsmodel',
            name='language',
            field=models.CharField(choices=[('en-us', 'english-us'), ('en-br', 'english-britain')], default='en-us', max_length=50),
        ),
    ]
