# Generated by Django 5.1.6 on 2025-09-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TTSStudio', '0009_voice_model_alter_ttsmodel_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voice',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('neutral', 'Neutral')], max_length=10),
        ),
    ]
