# Generated by Django 5.1.6 on 2025-09-30 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TTSStudio', '0010_alter_voice_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voice',
            name='model',
        ),
        migrations.AddField(
            model_name='voice',
            name='tts_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_voice_owner', to='TTSStudio.ttsmodel'),
        ),
    ]
