# Generated by Django 5.1.6 on 2025-09-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TTSStudio', '0011_remove_voice_model_voice_tts_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttssession',
            name='ttsmodel_size',
            field=models.CharField(choices=[('large', 'Large'), ('medium', 'Medium'), ('small', 'Small')], default='Medium', max_length=30),
        ),
    ]
