# Generated by Django 5.1.6 on 2025-09-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium')], max_length=20)),
                ('characters_used', models.IntegerField(default=0)),
                ('characters_limit', models.IntegerField()),
                ('renews_on', models.DateField()),
            ],
        ),
    ]
