"""
Django settings for EchoVerse project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

# import os
import sys
from pathlib import Path

# from datetime import timedelta
import socket

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-4apel#e+*3a5$p(@m8n=3ahuh2%o3_59f#5r_2onygr_z)*cu+"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = ["localhost", "127.0.0.1", "192.168.43.234"]

try:
    ip = socket.gethostbyname(socket.gethostname())
    ALLOWED_HOSTS.append(ip)
except Exception:
    pass

# Development only
# CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SECURE = False  # Set to True in production

FRONTEND_BASE_URL = "http://192.168.43.234:3001"

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3001",  # React frontend
    "http://127.0.0.1:3001",
    "http://192.168.43.234:3001",
]

CSRF_COOKIE_NAME = "csrftoken"
CSRF_HEADER_NAME = "HTTP_X_CSRFTOKEN"

# Model config
MODEL_ROOT = BASE_DIR / "pretrained_models"
TTS_URL = MODEL_ROOT / "tts_models"
HIFIGAN_URL = MODEL_ROOT / "hifi_gan"

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    # "widget_tweaks",
    "Users",
    "Converter",
    "Editor",
    "Subscription",
]

AUTH_USER_MODEL = "Users.EchoVerseUser"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "EchoVerse.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "EchoVerse.wsgi.application"


AUTHENTICATION_BACKENDS = [
    # "users.auth_backends.UsernameOrEmailAuthBackend",  # Custom backend
    "django.contrib.auth.backends.ModelBackend",  # Default backend
]

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

if "test" in sys.argv:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": ":memory:",
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": "EchoVerse",
            "USER": "skye",
            "PORT": "5432",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.TokenAuthentication",
    ],
    # 'DEFAULT_PERMISSION_CLASSES': [
    #   'rest_framework.permissions.IsAuthenticated',
    # ],
}

"""
NINJA_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
}
"""

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Africa/Nairobi"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# APPEND_SLASH = False

STATIC_URL = "static/"

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",  # finds files in STATICFILES_DIRS
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",  # finds static/ in each app
    # "compressor.finders.CompressorFinder",  # keeps compressor integration
]

# Media settings for file uploads
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

UPLOAD_URL = "/uploads/"
UPLOAD_PATH = BASE_DIR / UPLOAD_URL

DOCUMENT_URL = "/documents/"
DOCUMENTS_ROOT = BASE_DIR / "documents"


# email verification
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587  # Commonly used ports are 587 (TLS) or 465 (SSL)
EMAIL_USE_TLS = True  # Set to True for port 587, False for port 465
# EMAIL_USE_SSL = False  # Set to True for port 465, False for port 587
EMAIL_HOST_USER = "EchoVerse.tech@gmail.com"

EMAIL_HOST_PASSWORD = "vkcjyzwbzlgbwgzz"


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "file": {
            "level": "ERROR",
            "class": "logging.FileHandler",
            "filename": "error.log",
            "formatter": "verbose",
        },
        "console": {
            "level": "ERROR",
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["file", "console"],
            "level": "ERROR",
            "propagate": True,
        },
    },
}
